### ISSUE TITLE
Error Traceback and TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by 0xtbug** [aliharslan0/pyrevanced#1]
Hi, when i run this script got this error:

> root@vm:~/pyrevanced# python3 main.py 
> Traceback (most recent call last):
>   File "main.py", line 71, in <module>
>     class Patches:
>   File "main.py", line 88, in Patches
>     def get(self, music: bool) -> tuple[list[dict[str, str]], str]:
> TypeError: 'type' object is not subscriptable

**Comment by alihakanarslan** [comment]
What is your python version?
Probably your python is old, so either update Python or delete ` -> tuple[list[dict[str, str]], str]`.

**Comment by 0xtbug** [comment]
I'm using version 3.8 and I upgraded to version 3.10 but the error appears again as follows:
```
root@vmi922638:~/pyrevanced# python3.10 main.py 
Youtube or Youtube Music? [YT/YTM]: YT
Traceback (most recent call last):
  File "/root/pyrevanced/main.py", line 172, in <module>
    main()
  File "/root/pyrevanced/main.py", line 159, in main
    app_patches, version = patches.get((music := app == 'ytm'))
  File "/root/pyrevanced/main.py", line 90, in get
    version = next(i['version'] for i in patches if i['version'] != 'all')
StopIteration
```

**Comment by alihakanarslan** [comment]
I made a few changes, now it should work.

**Comment by 0xtbug** [comment]
thanks!, now the code is working

```
root@vmi922638:~/pyrevanced# python3.10 main.py 
Youtube or Youtube Music? [YT/YTM]: YT
[00] swipe-controls               : Adds volume and brightness swipe controls.
[01] seekbar-tapping              : Enables tap-to-seek on the seekbar of the video player.
[02] minimized-playback           : Enables minimized and background playback.
[03] amoled                       : Enables pure black theme.
[04] disable-create-button        : Hides the create button in the navigation bar.
[05] hide-cast-button             : Hides the cast button in the video player.
[06] return-youtube-dislike       : Shows the dislike count of videos using the Return YouTube Dislike API.
[07] hide-autoplay-button         : Hides the autoplay button in the video player.
[08] premium-heading              : Shows premium branding on the home screen.
[09] custom-branding              : Changes the YouTube launcher icon to be ReVanced's.
[10] disable-fullscreen-panels    : Disables video description and comments panel in fullscreen view.
[11] old-quality-layout           : Enables the original quality flyout menu.
[12] hide-shorts-button           : Hides the shorts button on the navigation bar.
[13] hide-watermark               : Hides creator's watermarks on videos.
[14] sponsorblock                 : Integrate SponsorBlock.
[15] enable-wide-searchbar        : Replaces the search icon with a wide search bar. This will hide the YouTube logo when active.
[16] force-vp9-codec              : Forces the VP9 codec for videos.
[17] always-autorepeat            : Always repeats the playing video again.
[18] microg-support               : Allows YouTube ReVanced to run without root and under a different package name with Vanced MicroG
[19] enable-debugging             : Enables app debugging by patching the manifest file.
[20] custom-playback-speed        : Adds more video playback speed options.
[21] hdr-auto-brightness          : Makes the brightness of HDR videos follow the system default.
[22] remember-video-quality       : Adds the ability to remember the video quality you chose in the video quality flyout.
[23] video-ads                    : Removes ads in the video player.
[24] general-ads                  : Removes general ads.
[25] hide-infocard-suggestions    : Hides infocards in videos.
Select the patches you want as "3 24 2 ...":
```
